# Univariate data {#univariate}

```{R setup, include=FALSE}
require(UsingR)
```


## Levels of measurement {-}

The view in most textbooks is from Stanley Smith Stevens (1964)

::: {.definition}
**Nominal**  
Such data is qualitative or descriptive, but not numeric. An example might be the name of a person or the town they are from, or the number on a bib a runner wears in a race.
:::

::: {.definition}
**Ordinal**  
Ordinal data is data with some order, so that we can sort the data from largest to smallest. An example might be the place a runner takes in a race.
:::

::: {.definition}
**Interval**  
Interval data is ordinal data where the difference between two values has some interpretation. The clock time a person finishes might be an example. If we know runner a finishes at noon and runner B at 1PM then we know that runner B took longer. Since we haven’t specified when they started, we don’t know what percent longer though.
:::

::: {.definition}
**Ratio**  
Ration data has a meaningful 0. If we record not the time of finishing, but the time since starting, then 0 has a meaning and we can take a ration of the total time for runner A and B to compare the two.
:::

However, working with data on a computer is different, requiring different categories...

::: {.definition}
**Factor**  
When we look at many variables, some may simply record categories used to group the data. In R we will use *factors* to store these variables. An example might be the browser a user has used to view a website, as gleaned from a log.
:::

::: {.definition}
**character**  
Some categorical data are factors, but others are really just identifiers, and are not used for grouping. An example might be a user’s IP address. Difference can be thought of as distinguishing between *categorizing* a case or *characterizing* a case. While both factor and categorical data are *nominal*, we keep the distinction as we will interact with the data differently.
:::

::: {.definition}
**discrete**  
Discrete data comes from measurements where there are essentially only distinct and separate possible values that can be counted. For example, the number of visits a person makes to a website will always be integer data, as will other counting data.
:::

::: {.definition}
**continuous**  
Data which could conceivably come from a continuum of variables. The recording of time in milliseconds of a visit to a website might be such data. A useful distinction is that for discrete data we expect that cases will share values, whereas for continuous data this will be impossible, or at least very unlikely. We can also turn continuous data into discrete data by truncating (record the minute instead of the millisecond) or by binning.Rather than draw distinctions between ordinal, interval, and ratio, it is more important for statistical theory - in finding a model for the recorded data - to know if the data is discrete or continuous.
:::

::: {.definition}
**time and date**  
Though we just saw that time and date can be considered continuous or discrete, for computers there are often separate ways to handle date and time data. Issues that complicate matters are leap days and time zones, but also scale (some people want millisecond data)
:::

::: {.definition}
**hierarchical**  
while much data is several measurements for several cases and fits nicely onto a rectangular spreadsheet, data on networks does not fit this
:::

## Data Vectors

Suppose the number of whale beachings in Texas during the 1990s was

`74 122 235 111 292 111 211 133 156 79`

We can combine these into a data set through

```{R}
whale <- c(74, 122, 235, 111, 292, 111, 211, 133, 156, 79)
```

 The `whale` object is a *data vector*.

the size of the data set is retreived with the `length` function

```{R}
length(whale)
```

```{R}
sum(whale)
```

Average can be found with combining the two...

```{R}
sum(whale)/length(whale)
```
or

```{R}
mean(whale)
```

### Vectorization

The arithmetic operations and the mathematical functions are vectorized, in that they will be called for each element in a data vector.

```{R}
whale - mean(whale)
```

```{R}
whale^2 / length(whale)
```

```{R}
sqrt(whale)
```

### Missing values

```{R}
hipcost <- c(10500, 45000, 74100, NA, 83500, 86000, 38200, NA, 44300, 12500, 55700, 43900, 71900, NA, 62000)
```

NA is interpreted as a missing value, but which may have meaning, so it is not 0

```{R}
sum(hipcost)
```

- leads to NA
- solution is to use na.rm

```{R}
sum(hipcost, na.rm = TRUE)
```

```{R}
mean(hipcost, na.rm = TRUE)
```

- multivariate datasets have more options related to NA values

### Attributes: names

```{r}
head(precip)
```
```{R}
head(sort(precip, decreasing=TRUE))
```

```{R}
head(names(precip))
```

### Structured Data

```{R}
1:length(whale)
```

```{R}
0:length(whale)-1
```
```{R}

0:(length(whale)-1)
```

...

## Numeric summaries

### Center 

- most common - mean, median, mode

```{R}
wts <- kid.weights
```

```{R}
sort(wts$weight, decreasing = TRUE)
```

- sample mean known as `x bar` or $\bar{x}$

```{R}
mean(wts$weight)
```
### Spread

- variability of the data

#### `sample variance`

$$
s^2=\frac{1}{n-1}\sum_{i}(x_i-\bar{x})^2
$$
```{R}
var(wts$weight)
```

#### Sample `standard deviation`

$$
\sqrt{s^2}=\sqrt{\frac{1}{n-1}\sum_{i}(x_i-\bar{x})^2}
$$

```{R}
sd(hipcost, na.rm=TRUE)
```

#### `z-score`

- deviations, $d_i=x_i-\bar{x}$, express data relative to its centre, rather than absolute
$$
z-score=\frac{x_i-\bar{x}}{s}
$$
gives the size of the data point in terms of its relative position to centre on a scale of standard deviations, so z-score of 3 means the data point is 3sd larger than mean

#### defining function
```{R}
z_score <- function(x)(x-mean(x))/sd(x)
```

```{R}
z_score(wts$weight)
```

Example 

Prof scales on z-scores and those who have z-score value of greater than 1.28, get an A

```{R}
x <- c(54, 50, 79, 79, 51, 69, 55, 62, 100, 80)
z <- (x-mean(x))/sd(x)
x[z >= 1.28]
```

what score is just good enough for an A?

```{R}
mean(x) + 1.28 * sd(x)
```

- formula reverses the z-score formula is read as the score which is 1.28 SD above the mean
- z-score allow datasets with different scales to be compared

### Shape (distribution)

- normal

## categorical data


```{R}
x <- babies$smoke
x <- factor(x, labels=c("never", "now", "until current", "once, quit", "unknown" ))
table(x)
```

```{R}
out <- table(x)
prop <- 100 * out / sum(out)
round(prop, digits = 2)
```
